const { VITE_GOOGLE_AOUTH_URL, VITE_GOOGLE_OAUTH_CLIENT_ID, VITE_GOOGLE_AOUTH_REDIRECT_SERVER } =
  import.meta.env as { [key: string]: string }

const OAUTH = {
  GOOGLE_URL: VITE_GOOGLE_AOUTH_URL,
  GOOGLE_CLIENT_ID: VITE_GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_REDIRECT_SERVER: VITE_GOOGLE_AOUTH_REDIRECT_SERVER
} as const

export default OAUTH
