const {
  VITE_GOOGLE_OAUTH_AUTH_URL,
  VITE_GOOGLE_OAUTH_CLIENT_ID,
  VITE_GOOGLE_OAUTH_REDIRECT_SERVER,
  VITE_GOOGLE_TOKEN_UTL,
  VITE_GOOGLE_CLIENT_SECRET
} = import.meta.env as { [key: string]: string }

const OAUTH = {
  GOOGLE_URL: VITE_GOOGLE_OAUTH_AUTH_URL,
  GOOGLE_CLIENT_ID: VITE_GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_REDIRECT_SERVER_URL: VITE_GOOGLE_OAUTH_REDIRECT_SERVER,

  GOOGLE_TOKEN_URL: VITE_GOOGLE_TOKEN_UTL,
  GOOGLE_CLIENT_SECRET: VITE_GOOGLE_CLIENT_SECRET
} as const

export default OAUTH
